import { defineConfig } from "orval";

const input = process.env.OPENAPI_URL ?? "http://localhost:5213/openapi/v1.json";

export default defineConfig({
  dashboard: {
    input,
    output: {
      target: "src/api/generated.ts",
      client: "react-query",
      httpClient: "fetch",
      clean: true,
      override: {
        header: () => [
          "Generated by Orval.",
          "Do not edit manually."
        ],
        query: {
          useQuery: true,
          useMutation: true
        }
      }
    }
  }
});
