/**
 * Generated by Orval.
 * Do not edit manually.
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

export interface ChatDashboardMessage {
  id: string;
  role: string;
  content: string;
  htmlContent: string;
  createdAt: string;
}

export type ChatDashboardSnapshotQueuedPrompt = null | string;

export interface ChatDashboardSnapshot {
  conversationId: string;
  messages: ChatDashboardMessage[];
  recentEvents: RunEventRow[];
  injectedMemories: MemoryRow[];
  activeTools: string[];
  provider: string;
  model: string;
  isRunning: boolean;
  queuedPrompt: ChatDashboardSnapshotQueuedPrompt;
}

export interface MemoryGraphEdge {
  id: string;
  sourceId: string;
  targetId: string;
  kind: string;
  label: string;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type MemoryGraphNodeImportance = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type MemoryGraphNodeCount = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type MemoryGraphNodeSize = number | string;

export type MemoryGraphNodeMetadata = {[key: string]: string};

export interface MemoryGraphNode {
  id: string;
  label: string;
  kind: string;
  segment: string;
  tier: string;
  lifecycle: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  importance: MemoryGraphNodeImportance;
  text: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  count: MemoryGraphNodeCount;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  size: MemoryGraphNodeSize;
  metadata: MemoryGraphNodeMetadata;
}

export interface MemoryGraphSnapshot {
  nodes: MemoryGraphNode[];
  edges: MemoryGraphEdge[];
  emptyReason: string;
}

export interface MemoryLifecycleUpdateDto {
  lifecycle: string;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type MemoryRowImportance = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type MemoryRowConfidence = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type MemoryRowAccessCount = number | string;

export type MemoryRowLastAccessedAt = null | string;

export type MemoryRowSourceMessageId = null | string;

export type MemoryRowSupersedes = null | string;

export interface MemoryRow {
  id: string;
  text: string;
  tier: string;
  segment: string;
  lifecycle: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  importance: MemoryRowImportance;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  confidence: MemoryRowConfidence;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  accessCount: MemoryRowAccessCount;
  createdAt: string;
  updatedAt: string;
  lastAccessedAt: MemoryRowLastAccessedAt;
  sourceMessageId: MemoryRowSourceMessageId;
  supersedes: MemoryRowSupersedes;
  hasDuplicateText: boolean;
}

export interface MemoryWorkspaceSnapshot {
  memories: MemoryRow[];
  lifecycles: string[];
  segments: string[];
  tiers: string[];
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type MemoryWriteDtoImportance = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
 */
export type MemoryWriteDtoConfidence = number | string;

export interface MemoryWriteDto {
  text: string;
  tier: string;
  segment: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  importance: MemoryWriteDtoImportance;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  confidence: MemoryWriteDtoConfidence;
}

export type RunEventRowMetadata = {[key: string]: string};

export interface RunEventRow {
  id: string;
  kind: string;
  phase: string;
  conversationId: string;
  createdAt: string;
  summary: string;
  metadata: RunEventRowMetadata;
  isError: boolean;
}

export type RunTimelineSnapshotConversationId = null | string;

export interface RunTimelineSnapshot {
  conversationId: RunTimelineSnapshotConversationId;
  turns: RunTurnGroup[];
  events: RunEventRow[];
}

export interface RunTurnGroup {
  title: string;
  startedAt: string;
  events: RunEventRow[];
}

export interface SendChatMessageRequest {
  prompt: string;
}

export type SendChatMessageResponseErrorMessage = null | string;

export interface SendChatMessageResponse {
  snapshot: ChatDashboardSnapshot;
  errorMessage: SendChatMessageResponseErrorMessage;
}

export type SettingsDashboardSnapshotValues = {[key: string]: string};

export interface SettingsDashboardSnapshot {
  values: SettingsDashboardSnapshotValues;
  appliedLayers: string[];
  memoryConnectionString: string;
}

export type GetRunsParams = {
conversationId?: string;
filter?: string;
};

export type GetMemoriesParams = {
query?: string;
lifecycle?: string;
segment?: string;
tier?: string;
};

export type getMainChatResponse200 = {
  data: ChatDashboardSnapshot
  status: 200
}
    
export type getMainChatResponseSuccess = (getMainChatResponse200) & {
  headers: Headers;
};
;

export type getMainChatResponse = (getMainChatResponseSuccess)

export const getGetMainChatUrl = () => {


  

  return `/api/dashboard/chat/main`
}

export const getMainChat = async ( options?: RequestInit): Promise<getMainChatResponse> => {
  
  const res = await fetch(getGetMainChatUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMainChatResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMainChatResponse
}





export const getGetMainChatQueryKey = () => {
    return [
    `/api/dashboard/chat/main`
    ] as const;
    }

    
export const getGetMainChatQueryOptions = <TData = Awaited<ReturnType<typeof getMainChat>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMainChat>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMainChatQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMainChat>>> = ({ signal }) => getMainChat({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMainChat>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMainChatQueryResult = NonNullable<Awaited<ReturnType<typeof getMainChat>>>
export type GetMainChatQueryError = unknown


export function useGetMainChat<TData = Awaited<ReturnType<typeof getMainChat>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMainChat>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMainChat>>,
          TError,
          Awaited<ReturnType<typeof getMainChat>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMainChat<TData = Awaited<ReturnType<typeof getMainChat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMainChat>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMainChat>>,
          TError,
          Awaited<ReturnType<typeof getMainChat>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMainChat<TData = Awaited<ReturnType<typeof getMainChat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMainChat>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMainChat<TData = Awaited<ReturnType<typeof getMainChat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMainChat>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMainChatQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export type sendMainChatMessageResponse200 = {
  data: SendChatMessageResponse
  status: 200
}
    
export type sendMainChatMessageResponseSuccess = (sendMainChatMessageResponse200) & {
  headers: Headers;
};
;

export type sendMainChatMessageResponse = (sendMainChatMessageResponseSuccess)

export const getSendMainChatMessageUrl = () => {


  

  return `/api/dashboard/chat/main/messages`
}

export const sendMainChatMessage = async (sendChatMessageRequest: SendChatMessageRequest, options?: RequestInit): Promise<sendMainChatMessageResponse> => {
  
  const res = await fetch(getSendMainChatMessageUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sendChatMessageRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sendMainChatMessageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sendMainChatMessageResponse
}




export const getSendMainChatMessageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendMainChatMessage>>, TError,{data: SendChatMessageRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof sendMainChatMessage>>, TError,{data: SendChatMessageRequest}, TContext> => {

const mutationKey = ['sendMainChatMessage'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendMainChatMessage>>, {data: SendChatMessageRequest}> = (props) => {
          const {data} = props ?? {};

          return  sendMainChatMessage(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SendMainChatMessageMutationResult = NonNullable<Awaited<ReturnType<typeof sendMainChatMessage>>>
    export type SendMainChatMessageMutationBody = SendChatMessageRequest
    export type SendMainChatMessageMutationError = unknown

    export const useSendMainChatMessage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendMainChatMessage>>, TError,{data: SendChatMessageRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendMainChatMessage>>,
        TError,
        {data: SendChatMessageRequest},
        TContext
      > => {

      const mutationOptions = getSendMainChatMessageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export type streamMainChatMessageResponse200 = {
  data: void
  status: 200
}
    
export type streamMainChatMessageResponseSuccess = (streamMainChatMessageResponse200) & {
  headers: Headers;
};
;

export type streamMainChatMessageResponse = (streamMainChatMessageResponseSuccess)

export const getStreamMainChatMessageUrl = () => {


  

  return `/api/dashboard/chat/main/stream`
}

export const streamMainChatMessage = async (sendChatMessageRequest: SendChatMessageRequest, options?: RequestInit): Promise<streamMainChatMessageResponse> => {
  
  const res = await fetch(getStreamMainChatMessageUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sendChatMessageRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: streamMainChatMessageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as streamMainChatMessageResponse
}




export const getStreamMainChatMessageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof streamMainChatMessage>>, TError,{data: SendChatMessageRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof streamMainChatMessage>>, TError,{data: SendChatMessageRequest}, TContext> => {

const mutationKey = ['streamMainChatMessage'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof streamMainChatMessage>>, {data: SendChatMessageRequest}> = (props) => {
          const {data} = props ?? {};

          return  streamMainChatMessage(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StreamMainChatMessageMutationResult = NonNullable<Awaited<ReturnType<typeof streamMainChatMessage>>>
    export type StreamMainChatMessageMutationBody = SendChatMessageRequest
    export type StreamMainChatMessageMutationError = unknown

    export const useStreamMainChatMessage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof streamMainChatMessage>>, TError,{data: SendChatMessageRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof streamMainChatMessage>>,
        TError,
        {data: SendChatMessageRequest},
        TContext
      > => {

      const mutationOptions = getStreamMainChatMessageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export type getRunsResponse200 = {
  data: RunTimelineSnapshot
  status: 200
}
    
export type getRunsResponseSuccess = (getRunsResponse200) & {
  headers: Headers;
};
;

export type getRunsResponse = (getRunsResponseSuccess)

export const getGetRunsUrl = (params?: GetRunsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/dashboard/runs?${stringifiedParams}` : `/api/dashboard/runs`
}

export const getRuns = async (params?: GetRunsParams, options?: RequestInit): Promise<getRunsResponse> => {
  
  const res = await fetch(getGetRunsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getRunsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRunsResponse
}





export const getGetRunsQueryKey = (params?: GetRunsParams,) => {
    return [
    `/api/dashboard/runs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRunsQueryOptions = <TData = Awaited<ReturnType<typeof getRuns>>, TError = unknown>(params?: GetRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRuns>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRunsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRuns>>> = ({ signal }) => getRuns(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRuns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRunsQueryResult = NonNullable<Awaited<ReturnType<typeof getRuns>>>
export type GetRunsQueryError = unknown


export function useGetRuns<TData = Awaited<ReturnType<typeof getRuns>>, TError = unknown>(
 params: undefined |  GetRunsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRuns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRuns>>,
          TError,
          Awaited<ReturnType<typeof getRuns>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRuns<TData = Awaited<ReturnType<typeof getRuns>>, TError = unknown>(
 params?: GetRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRuns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRuns>>,
          TError,
          Awaited<ReturnType<typeof getRuns>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRuns<TData = Awaited<ReturnType<typeof getRuns>>, TError = unknown>(
 params?: GetRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRuns>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetRuns<TData = Awaited<ReturnType<typeof getRuns>>, TError = unknown>(
 params?: GetRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRuns>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRunsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export type getMemoriesResponse200 = {
  data: MemoryWorkspaceSnapshot
  status: 200
}
    
export type getMemoriesResponseSuccess = (getMemoriesResponse200) & {
  headers: Headers;
};
;

export type getMemoriesResponse = (getMemoriesResponseSuccess)

export const getGetMemoriesUrl = (params?: GetMemoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/dashboard/memories?${stringifiedParams}` : `/api/dashboard/memories`
}

export const getMemories = async (params?: GetMemoriesParams, options?: RequestInit): Promise<getMemoriesResponse> => {
  
  const res = await fetch(getGetMemoriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMemoriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMemoriesResponse
}





export const getGetMemoriesQueryKey = (params?: GetMemoriesParams,) => {
    return [
    `/api/dashboard/memories`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetMemoriesQueryOptions = <TData = Awaited<ReturnType<typeof getMemories>>, TError = unknown>(params?: GetMemoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemories>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMemoriesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMemories>>> = ({ signal }) => getMemories(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMemories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMemoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getMemories>>>
export type GetMemoriesQueryError = unknown


export function useGetMemories<TData = Awaited<ReturnType<typeof getMemories>>, TError = unknown>(
 params: undefined |  GetMemoriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMemories>>,
          TError,
          Awaited<ReturnType<typeof getMemories>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMemories<TData = Awaited<ReturnType<typeof getMemories>>, TError = unknown>(
 params?: GetMemoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMemories>>,
          TError,
          Awaited<ReturnType<typeof getMemories>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMemories<TData = Awaited<ReturnType<typeof getMemories>>, TError = unknown>(
 params?: GetMemoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemories>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMemories<TData = Awaited<ReturnType<typeof getMemories>>, TError = unknown>(
 params?: GetMemoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMemories>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMemoriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export type writeMemoryResponse200 = {
  data: MemoryRow
  status: 200
}
    
export type writeMemoryResponseSuccess = (writeMemoryResponse200) & {
  headers: Headers;
};
;

export type writeMemoryResponse = (writeMemoryResponseSuccess)

export const getWriteMemoryUrl = () => {


  

  return `/api/dashboard/memories`
}

export const writeMemory = async (memoryWriteDto: MemoryWriteDto, options?: RequestInit): Promise<writeMemoryResponse> => {
  
  const res = await fetch(getWriteMemoryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      memoryWriteDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: writeMemoryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as writeMemoryResponse
}




export const getWriteMemoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof writeMemory>>, TError,{data: MemoryWriteDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof writeMemory>>, TError,{data: MemoryWriteDto}, TContext> => {

const mutationKey = ['writeMemory'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof writeMemory>>, {data: MemoryWriteDto}> = (props) => {
          const {data} = props ?? {};

          return  writeMemory(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type WriteMemoryMutationResult = NonNullable<Awaited<ReturnType<typeof writeMemory>>>
    export type WriteMemoryMutationBody = MemoryWriteDto
    export type WriteMemoryMutationError = unknown

    export const useWriteMemory = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof writeMemory>>, TError,{data: MemoryWriteDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof writeMemory>>,
        TError,
        {data: MemoryWriteDto},
        TContext
      > => {

      const mutationOptions = getWriteMemoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export type updateMemoryLifecycleResponse200 = {
  data: MemoryRow
  status: 200
}
    
export type updateMemoryLifecycleResponseSuccess = (updateMemoryLifecycleResponse200) & {
  headers: Headers;
};
;

export type updateMemoryLifecycleResponse = (updateMemoryLifecycleResponseSuccess)

export const getUpdateMemoryLifecycleUrl = (id: string,) => {


  

  return `/api/dashboard/memories/${id}/lifecycle`
}

export const updateMemoryLifecycle = async (id: string,
    memoryLifecycleUpdateDto: MemoryLifecycleUpdateDto, options?: RequestInit): Promise<updateMemoryLifecycleResponse> => {
  
  const res = await fetch(getUpdateMemoryLifecycleUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      memoryLifecycleUpdateDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateMemoryLifecycleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateMemoryLifecycleResponse
}




export const getUpdateMemoryLifecycleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMemoryLifecycle>>, TError,{id: string;data: MemoryLifecycleUpdateDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateMemoryLifecycle>>, TError,{id: string;data: MemoryLifecycleUpdateDto}, TContext> => {

const mutationKey = ['updateMemoryLifecycle'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMemoryLifecycle>>, {id: string;data: MemoryLifecycleUpdateDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateMemoryLifecycle(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMemoryLifecycleMutationResult = NonNullable<Awaited<ReturnType<typeof updateMemoryLifecycle>>>
    export type UpdateMemoryLifecycleMutationBody = MemoryLifecycleUpdateDto
    export type UpdateMemoryLifecycleMutationError = unknown

    export const useUpdateMemoryLifecycle = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMemoryLifecycle>>, TError,{id: string;data: MemoryLifecycleUpdateDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMemoryLifecycle>>,
        TError,
        {id: string;data: MemoryLifecycleUpdateDto},
        TContext
      > => {

      const mutationOptions = getUpdateMemoryLifecycleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export type deleteMemoryResponse200 = {
  data: void
  status: 200
}
    
export type deleteMemoryResponseSuccess = (deleteMemoryResponse200) & {
  headers: Headers;
};
;

export type deleteMemoryResponse = (deleteMemoryResponseSuccess)

export const getDeleteMemoryUrl = (id: string,) => {


  

  return `/api/dashboard/memories/${id}`
}

export const deleteMemory = async (id: string, options?: RequestInit): Promise<deleteMemoryResponse> => {
  
  const res = await fetch(getDeleteMemoryUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteMemoryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteMemoryResponse
}




export const getDeleteMemoryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMemory>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMemory>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteMemory'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMemory>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteMemory(id,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMemoryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMemory>>>
    
    export type DeleteMemoryMutationError = unknown

    export const useDeleteMemory = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMemory>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMemory>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteMemoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export type getGraphResponse200 = {
  data: MemoryGraphSnapshot
  status: 200
}
    
export type getGraphResponseSuccess = (getGraphResponse200) & {
  headers: Headers;
};
;

export type getGraphResponse = (getGraphResponseSuccess)

export const getGetGraphUrl = () => {


  

  return `/api/dashboard/graph`
}

export const getGraph = async ( options?: RequestInit): Promise<getGraphResponse> => {
  
  const res = await fetch(getGetGraphUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getGraphResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getGraphResponse
}





export const getGetGraphQueryKey = () => {
    return [
    `/api/dashboard/graph`
    ] as const;
    }

    
export const getGetGraphQueryOptions = <TData = Awaited<ReturnType<typeof getGraph>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraph>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGraphQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGraph>>> = ({ signal }) => getGraph({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGraph>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGraphQueryResult = NonNullable<Awaited<ReturnType<typeof getGraph>>>
export type GetGraphQueryError = unknown


export function useGetGraph<TData = Awaited<ReturnType<typeof getGraph>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraph>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGraph>>,
          TError,
          Awaited<ReturnType<typeof getGraph>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGraph<TData = Awaited<ReturnType<typeof getGraph>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraph>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGraph>>,
          TError,
          Awaited<ReturnType<typeof getGraph>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGraph<TData = Awaited<ReturnType<typeof getGraph>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraph>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGraph<TData = Awaited<ReturnType<typeof getGraph>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraph>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGraphQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export type getSettingsResponse200 = {
  data: SettingsDashboardSnapshot
  status: 200
}
    
export type getSettingsResponseSuccess = (getSettingsResponse200) & {
  headers: Headers;
};
;

export type getSettingsResponse = (getSettingsResponseSuccess)

export const getGetSettingsUrl = () => {


  

  return `/api/dashboard/settings`
}

export const getSettings = async ( options?: RequestInit): Promise<getSettingsResponse> => {
  
  const res = await fetch(getGetSettingsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSettingsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSettingsResponse
}





export const getGetSettingsQueryKey = () => {
    return [
    `/api/dashboard/settings`
    ] as const;
    }

    
export const getGetSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSettingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettings>>> = ({ signal }) => getSettings({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getSettings>>>
export type GetSettingsQueryError = unknown


export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettings>>,
          TError,
          Awaited<ReturnType<typeof getSettings>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettings>>,
          TError,
          Awaited<ReturnType<typeof getSettings>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
